apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: frontend-team

  source:
    repoURL: https://github.com/namanSingh101/apps-app.git
    targetRevision: main
    path: apps/

  destination:
    server: https://172.31.46.104:33893
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
