apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-child
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/namanSingh101/argocd-demos.git
    targetRevision: HEAD
    path: nginx/

  destination:
    server: https://172.31.46.104:33893
    namespace: frontend

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
